### ISSUE TITLE
[stage6] 장바구니 아이템 결제 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by useonglee** [useonglee/coupang-clone#53]
### TODO
1. [x] 장바구니 페이지에서 장바구니 아이템 결제 페이지로 이동 기능을 하는 버튼 구현
2. [x] 결제 페이지 레이아웃 구현
3. [x] typescript eslint 설정
